defmodule Core.Repo.Migrations.RemoveMultitenancy do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop(constraint(:workflows_versions, "workflows_versions_version_source_id_fkey"))

    alter table(:workflows_versions) do
      modify(
        :version_source_id,
        references(:workflows,
          column: :id,
          name: "workflows_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:workflows) do
      remove(:tenant_id)
    end

    drop(constraint(:workflow_runs_versions, "workflow_runs_versions_version_source_id_fkey"))

    alter table(:workflow_runs_versions) do
      modify(
        :version_source_id,
        references(:workflow_runs,
          column: :id,
          name: "workflow_runs_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:workflow_runs) do
      remove(:tenant_id)
    end

    drop(constraint(:workflow_runs, "workflow_runs_workflow_id_fkey"))

    drop(constraint(:workflow_runs, "workflow_runs_asset_id_fkey"))

    alter table(:workflow_runs) do
      modify(
        :asset_id,
        references(:assets,
          column: :id,
          name: "workflow_runs_asset_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :workflow_id,
        references(:workflows,
          column: :id,
          name: "workflow_runs_workflow_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop(constraint(:permissions_versions, "permissions_versions_version_source_id_fkey"))

    alter table(:permissions_versions) do
      modify(
        :version_source_id,
        references(:permissions,
          column: :id,
          name: "permissions_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:permissions) do
      remove(:tenant_id)
    end

    drop(constraint(:permissions, "permissions_asset_id_fkey"))

    alter table(:permissions) do
      modify(
        :asset_id,
        references(:assets,
          column: :id,
          name: "permissions_asset_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop(constraint(:metadata_values_versions, "metadata_values_versions_version_source_id_fkey"))

    alter table(:metadata_values_versions) do
      modify(
        :version_source_id,
        references(:metadata_values,
          column: :id,
          name: "metadata_values_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:metadata_values) do
      remove(:tenant_id)
    end

    drop(constraint(:metadata_values, "metadata_values_schema_id_fkey"))

    drop(constraint(:metadata_values, "metadata_values_asset_id_fkey"))

    alter table(:metadata_values) do
      modify(
        :asset_id,
        references(:assets,
          column: :id,
          name: "metadata_values_asset_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :schema_id,
        references(:metadata_schemas,
          column: :id,
          name: "metadata_values_schema_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop(
      constraint(:metadata_schemas_versions, "metadata_schemas_versions_version_source_id_fkey")
    )

    alter table(:metadata_schemas_versions) do
      modify(
        :version_source_id,
        references(:metadata_schemas,
          column: :id,
          name: "metadata_schemas_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:metadata_schemas) do
      remove(:tenant_id)
    end

    drop(constraint(:assets_versions, "assets_versions_version_source_id_fkey"))

    alter table(:assets_versions) do
      modify(
        :version_source_id,
        references(:assets,
          column: :id,
          name: "assets_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:assets) do
      remove(:tenant_id)
    end

    drop(constraint(:asset_links_versions, "asset_links_versions_version_source_id_fkey"))

    alter table(:asset_links_versions) do
      modify(
        :version_source_id,
        references(:asset_links,
          column: :id,
          name: "asset_links_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:asset_links) do
      remove(:tenant_id)
    end

    drop(constraint(:asset_links, "asset_links_child_id_fkey"))

    drop(constraint(:asset_links, "asset_links_parent_id_fkey"))

    alter table(:asset_links) do
      modify(
        :parent_id,
        references(:assets,
          column: :id,
          name: "asset_links_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :child_id,
        references(:assets,
          column: :id,
          name: "asset_links_child_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end

  def down do
    drop(constraint(:asset_links, "asset_links_parent_id_fkey"))

    drop(constraint(:asset_links, "asset_links_child_id_fkey"))

    alter table(:asset_links) do
      modify(
        :child_id,
        references(:assets,
          column: :id,
          name: "asset_links_child_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :parent_id,
        references(:assets,
          column: :id,
          name: "asset_links_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:asset_links) do
      add(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "asset_links_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    drop(constraint(:asset_links_versions, "asset_links_versions_version_source_id_fkey"))

    alter table(:asset_links_versions) do
      modify(
        :version_source_id,
        references(:asset_links,
          column: :id,
          name: "asset_links_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:assets) do
      add(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "assets_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    drop(constraint(:assets_versions, "assets_versions_version_source_id_fkey"))

    alter table(:assets_versions) do
      modify(
        :version_source_id,
        references(:assets,
          column: :id,
          name: "assets_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:metadata_schemas) do
      add(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "metadata_schemas_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    drop(
      constraint(:metadata_schemas_versions, "metadata_schemas_versions_version_source_id_fkey")
    )

    alter table(:metadata_schemas_versions) do
      modify(
        :version_source_id,
        references(:metadata_schemas,
          column: :id,
          name: "metadata_schemas_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop(constraint(:metadata_values, "metadata_values_asset_id_fkey"))

    drop(constraint(:metadata_values, "metadata_values_schema_id_fkey"))

    alter table(:metadata_values) do
      modify(
        :schema_id,
        references(:metadata_schemas,
          column: :id,
          name: "metadata_values_schema_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :asset_id,
        references(:assets,
          column: :id,
          name: "metadata_values_asset_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:metadata_values) do
      add(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "metadata_values_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    drop(constraint(:metadata_values_versions, "metadata_values_versions_version_source_id_fkey"))

    alter table(:metadata_values_versions) do
      modify(
        :version_source_id,
        references(:metadata_values,
          column: :id,
          name: "metadata_values_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop(constraint(:permissions, "permissions_asset_id_fkey"))

    alter table(:permissions) do
      modify(
        :asset_id,
        references(:assets,
          column: :id,
          name: "permissions_asset_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:permissions) do
      add(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "permissions_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    drop(constraint(:permissions_versions, "permissions_versions_version_source_id_fkey"))

    alter table(:permissions_versions) do
      modify(
        :version_source_id,
        references(:permissions,
          column: :id,
          name: "permissions_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    drop(constraint(:workflow_runs, "workflow_runs_asset_id_fkey"))

    drop(constraint(:workflow_runs, "workflow_runs_workflow_id_fkey"))

    alter table(:workflow_runs) do
      modify(
        :workflow_id,
        references(:workflows,
          column: :id,
          name: "workflow_runs_workflow_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :asset_id,
        references(:assets,
          column: :id,
          name: "workflow_runs_asset_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:workflow_runs) do
      add(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "workflow_runs_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    drop(constraint(:workflow_runs_versions, "workflow_runs_versions_version_source_id_fkey"))

    alter table(:workflow_runs_versions) do
      modify(
        :version_source_id,
        references(:workflow_runs,
          column: :id,
          name: "workflow_runs_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:workflows) do
      add(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "workflows_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )
    end

    drop(constraint(:workflows_versions, "workflows_versions_version_source_id_fkey"))

    alter table(:workflows_versions) do
      modify(
        :version_source_id,
        references(:workflows,
          column: :id,
          name: "workflows_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end
  end
end
