defmodule Core.Repo.Migrations.AddAssetModelResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:workflows_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:workflows, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:workflows_versions) do
      modify(
        :version_source_id,
        references(:workflows,
          column: :id,
          name: "workflows_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:workflows) do
      add(:name, :text, null: false)
      add(:slug, :text, null: false)
      add(:asset_types, {:array, :text}, null: false, default: [])
      add(:definition, :map, null: false, default: %{})

      add(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "workflows_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:workflow_runs_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:workflow_runs, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:workflow_runs_versions) do
      modify(
        :version_source_id,
        references(:workflow_runs,
          column: :id,
          name: "workflow_runs_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:workflow_runs) do
      add(:asset_id, :uuid, null: false)
      add(:workflow_id, :uuid, null: false)
      add(:current_state, :text, null: false, default: "draft")
      add(:initiated_by, :uuid)
      add(:status, :text, null: false, default: "in_progress")
      add(:context, :map, null: false, default: %{})
      add(:tenant_id, :uuid, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:completed_at, :utc_datetime)
      add(:archived_at, :utc_datetime_usec)
    end

    create table(:permissions_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:permissions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:permissions_versions) do
      modify(
        :version_source_id,
        references(:permissions,
          column: :id,
          name: "permissions_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:permissions) do
      add(:asset_id, :uuid, null: false)
      add(:principal_id, :uuid, null: false)
      add(:principal_type, :text, null: false, default: "user")
      add(:level, :text, null: false)
      add(:tenant_id, :uuid, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:metadata_values_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:metadata_values, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:metadata_values_versions) do
      modify(
        :version_source_id,
        references(:metadata_values,
          column: :id,
          name: "metadata_values_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:metadata_values) do
      add(:asset_id, :uuid, null: false)
      add(:schema_id, :uuid, null: false)
      add(:values, :map, null: false, default: %{})
      add(:tenant_id, :uuid, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:metadata_schemas_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:metadata_schemas, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:metadata_schemas_versions) do
      modify(
        :version_source_id,
        references(:metadata_schemas,
          column: :id,
          name: "metadata_schemas_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:metadata_schemas) do
      add(:name, :text, null: false)
      add(:slug, :text, null: false)
      add(:schema, :map, null: false, default: %{})

      add(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "metadata_schemas_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:assets_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:assets, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:workflow_runs) do
      modify(
        :asset_id,
        references(:assets,
          column: :id,
          name: "workflow_runs_asset_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :workflow_id,
        references(:workflows,
          column: :id,
          name: "workflow_runs_workflow_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "workflow_runs_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:permissions) do
      modify(
        :asset_id,
        references(:assets,
          column: :id,
          name: "permissions_asset_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "permissions_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:metadata_values) do
      modify(
        :asset_id,
        references(:assets,
          column: :id,
          name: "metadata_values_asset_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :schema_id,
        references(:metadata_schemas,
          column: :id,
          name: "metadata_values_schema_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )

      modify(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "metadata_values_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:assets_versions) do
      modify(
        :version_source_id,
        references(:assets,
          column: :id,
          name: "assets_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:assets) do
      add(:type, :text, null: false)
      add(:role, :text)
      add(:state, :text, null: false, default: "draft")

      add(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "assets_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end

    create table(:asset_links_versions, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:version_action_type, :text, null: false)
      add(:version_action_name, :text, null: false)
      add(:version_source_id, :uuid, null: false)
      add(:changes, :map)

      add(:version_inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:version_updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:asset_links, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
    end

    alter table(:asset_links_versions) do
      modify(
        :version_source_id,
        references(:asset_links,
          column: :id,
          name: "asset_links_versions_version_source_id_fkey",
          type: :uuid,
          prefix: "public"
        )
      )
    end

    alter table(:asset_links) do
      add(
        :parent_id,
        references(:assets,
          column: :id,
          name: "asset_links_parent_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(
        :child_id,
        references(:assets,
          column: :id,
          name: "asset_links_child_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:link_type, :text, null: false, default: "secondary")

      add(
        :tenant_id,
        references(:tenants,
          column: :id,
          name: "asset_links_tenant_id_fkey",
          type: :uuid,
          prefix: "public"
        ),
        null: false
      )

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:archived_at, :utc_datetime_usec)
    end
  end

  def down do
    drop(constraint(:asset_links, "asset_links_parent_id_fkey"))

    drop(constraint(:asset_links, "asset_links_child_id_fkey"))

    drop(constraint(:asset_links, "asset_links_tenant_id_fkey"))

    alter table(:asset_links) do
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:tenant_id)
      remove(:link_type)
      remove(:child_id)
      remove(:parent_id)
    end

    drop(constraint(:asset_links_versions, "asset_links_versions_version_source_id_fkey"))

    alter table(:asset_links_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:asset_links))

    drop(table(:asset_links_versions))

    drop(constraint(:assets, "assets_tenant_id_fkey"))

    alter table(:assets) do
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:tenant_id)
      remove(:state)
      remove(:role)
      remove(:type)
    end

    drop(constraint(:assets_versions, "assets_versions_version_source_id_fkey"))

    alter table(:assets_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(constraint(:metadata_values, "metadata_values_asset_id_fkey"))

    drop(constraint(:metadata_values, "metadata_values_schema_id_fkey"))

    drop(constraint(:metadata_values, "metadata_values_tenant_id_fkey"))

    alter table(:metadata_values) do
      modify(:tenant_id, :uuid)
      modify(:schema_id, :uuid)
      modify(:asset_id, :uuid)
    end

    drop(constraint(:permissions, "permissions_asset_id_fkey"))

    drop(constraint(:permissions, "permissions_tenant_id_fkey"))

    alter table(:permissions) do
      modify(:tenant_id, :uuid)
      modify(:asset_id, :uuid)
    end

    drop(constraint(:workflow_runs, "workflow_runs_asset_id_fkey"))

    drop(constraint(:workflow_runs, "workflow_runs_workflow_id_fkey"))

    drop(constraint(:workflow_runs, "workflow_runs_tenant_id_fkey"))

    alter table(:workflow_runs) do
      modify(:tenant_id, :uuid)
      modify(:workflow_id, :uuid)
      modify(:asset_id, :uuid)
    end

    drop(table(:assets))

    drop(table(:assets_versions))

    drop(constraint(:metadata_schemas, "metadata_schemas_tenant_id_fkey"))

    alter table(:metadata_schemas) do
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:tenant_id)
      remove(:schema)
      remove(:slug)
      remove(:name)
    end

    drop(
      constraint(:metadata_schemas_versions, "metadata_schemas_versions_version_source_id_fkey")
    )

    alter table(:metadata_schemas_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:metadata_schemas))

    drop(table(:metadata_schemas_versions))

    alter table(:metadata_values) do
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:tenant_id)
      remove(:values)
      remove(:schema_id)
      remove(:asset_id)
    end

    drop(constraint(:metadata_values_versions, "metadata_values_versions_version_source_id_fkey"))

    alter table(:metadata_values_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:metadata_values))

    drop(table(:metadata_values_versions))

    alter table(:permissions) do
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:tenant_id)
      remove(:level)
      remove(:principal_type)
      remove(:principal_id)
      remove(:asset_id)
    end

    drop(constraint(:permissions_versions, "permissions_versions_version_source_id_fkey"))

    alter table(:permissions_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:permissions))

    drop(table(:permissions_versions))

    alter table(:workflow_runs) do
      remove(:archived_at)
      remove(:completed_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:tenant_id)
      remove(:context)
      remove(:status)
      remove(:initiated_by)
      remove(:current_state)
      remove(:workflow_id)
      remove(:asset_id)
    end

    drop(constraint(:workflow_runs_versions, "workflow_runs_versions_version_source_id_fkey"))

    alter table(:workflow_runs_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:workflow_runs))

    drop(table(:workflow_runs_versions))

    drop(constraint(:workflows, "workflows_tenant_id_fkey"))

    alter table(:workflows) do
      remove(:archived_at)
      remove(:updated_at)
      remove(:inserted_at)
      remove(:tenant_id)
      remove(:definition)
      remove(:asset_types)
      remove(:slug)
      remove(:name)
    end

    drop(constraint(:workflows_versions, "workflows_versions_version_source_id_fkey"))

    alter table(:workflows_versions) do
      modify(:version_source_id, :uuid)
    end

    drop(table(:workflows))

    drop(table(:workflows_versions))
  end
end
