defmodule Core.Accounts.Token do
  @moduledoc """
  Token resource for authentication tokens.

  Stores tokens generated by AshAuthentication for password reset,
  email confirmation, and API authentication.
  """
  use Ash.Resource,
    domain: Core.Domain,
    data_layer: AshPostgres.DataLayer,
    extensions: [
      AshJsonApi.Resource
    ]

  postgres do
    table("tokens")
    repo(Core.Repo)
  end

  attributes do
    uuid_primary_key(:id)

    # The purpose of this token
    attribute :purpose, :atom do
      allow_nil?(false)
      public?(true)
      # :confirm, :recover, :sign_in, :access, :refresh
    end

    # The user this token belongs to
    attribute :user_id, :uuid do
      allow_nil?(false)
      public?(true)
    end

    # The token itself (hashed)
    attribute :token, :string do
      allow_nil?(false)
      sensitive?(true)
    end

    # Expiration time
    attribute :exp, :utc_datetime do
      allow_nil?(true)
      public?(true)
    end

    # Additional context
    attribute :context, :map do
      allow_nil?(true)
      default(%{})
      public?(true)
    end

    create_timestamp(:inserted_at)
    update_timestamp(:updated_at)
  end

  relationships do
    belongs_to :user, Core.Accounts.User do
      allow_nil?(false)
      source_attribute(:user_id)
      destination_attribute(:id)
    end
  end

  actions do
    defaults([:read])

    # Tokens are typically created by AshAuthentication automatically
    create :create do
      primary?(true)
      accept([:purpose, :user_id, :token, :exp, :context])
      change Core.DomainEvents.PublishDomainEvent.publish_domain_event()
    end

    update :update do
      primary?(true)
      accept([:exp, :context])
      require_atomic?(false)
      change Core.DomainEvents.PublishDomainEvent.publish_domain_event()
    end

    destroy :destroy do
      primary?(true)
      require_atomic?(false)
      change Core.DomainEvents.PublishDomainEvent.publish_domain_event()
    end
  end

  code_interface do
    define(:create, action: :create)
    define(:read, action: :read)
    define(:update, action: :update)
    define(:destroy, action: :destroy)
  end
end
